apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-fulfilment-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1 # At max how many can be unavailable
      maxSurge: 1 # By how many the number of pods can exceed than number of replicas configured
  selector: 
    matchLabels:
      name: "loan-fulfilment-service" # Selector is a query to match the label and it should match to the pod's label
  template:
    metadata:
      name: loan-fulfilment-service
      labels:
        name: "loan-fulfilment-service"
    spec:
      containers:
      - image: com.swapnilsankla/loan-fulfilment-service:latest
        name: loan-fulfilment-service
        imagePullPolicy: IfNotPresent    
        env:
        - name: KAFKA_URL
          value: cp-kafka:9092
        - name: MONGO_URL
          value: mongodb://mongo:27017/loan-fulfilment-service
        - name: TRACER_HOST
          value: jaeger-internal
        - name: TRACER_PORT
          value: "6831"          