apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  serviceName: kafka
  selector: 
    matchLabels:
      name: "cp-kafka"
  template:
    metadata:
      name: kafka
      labels:
        name: "cp-kafka"
    spec:
      containers:
      - image: confluentinc/cp-kafka:latest
        name: kafka
        imagePullPolicy: IfNotPresent    
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "zookeeper:2181"
        - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
          value: "1"
        - name: "KAFKA_CREATE_TOPICS"
          value: needLoanEvent:2:2,loanOfferDataAvailableForLoanProcessing:2:2,customerDataAvailableForLoanProcessing:2:2,screeningDataAvailableForLoanProcessing:2:2  
        command:
        - sh
        - -exc
        - |
          export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \
          exec /etc/confluent/docker/run  
            
