version: "3.7"
services:
  mongo-service:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  admin-mongo-service:
    image: mrvautin/adminmongo
    container_name: adminmongo
    links: ['mongo-service:mongo']
    environment:
      CONN_NAME: 'localConnection'
      DB_HOST: 'mongo'
      HOST: 0.0.0.0
    ports:
      - 1234:1234

  business-configuration-service:
    image: com.swapnilsankla/business-configuration
    container_name: business-configuration
    depends_on:
      - mongo-service
    environment:
      - MONGO_DB_HOST=mongo

  customer-service:
    image: com.swapnilsankla/customer-service
    container_name: customer-service
    depends_on:
      - kafka
      - business-configuration-service
      - tracing
    ports:
      - 8081:8081
    environment:
      - MONGO_URL=mongodb://mongo:27017/customer-service
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: accesslog

  loan-gateway-service:
    image: com.swapnilsankla/loan-gateway
    container_name: loan-gateway
    depends_on:
      - kafka
      - tracing
    ports:
      - 8082:8082
    environment:
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: accesslog

  loan-offer-service:
    image: com.swapnilsankla/loan-offer-service
    container_name: loan-offer-service
    depends_on:
      - kafka
      - business-configuration-service
      - tracing
    ports:
      - 8083:8083
    environment:
      - MONGO_URL=mongodb://mongo:27017/loan-offer-service
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: accesslog

  screening-service:
    image: com.swapnilsankla/screening-service
    container_name: screening-service
    depends_on:
      - kafka
      - business-configuration-service
      - tracing
    ports:
      - 8084:8084
    environment:
      - MONGO_URL=mongodb://mongo:27017/screening-service
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: accesslog

  loan-fulfilment-service:
    image: com.swapnilsankla/loan-fulfilment-service
    container_name: loan-fulfilment-service
    depends_on:
      - kafka
      - mongo-service
      - tracing
    ports:
      - 8085:8085
    environment:
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: accesslog

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: needLoanEvent:1:1,loanOfferDataAvailableForLoanProcessing:1:1,customerDataAvailableForLoanProcessing:1:1,screeningDataAvailableForLoanProcessing:1:1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090/tcp
    links:
      - kafka
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    depends_on:
      - customer-service

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - customer-service

  tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 5775:5775/udp

  fluentd:
    build: config/fluentd
    container_name: fluentd
    volumes:
      - ./config/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    expose:
      - 9200
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
