version: "3.7"
services:
  mongo-service:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  admin-mongo-service:
    image: mrvautin/adminmongo
    container_name: adminmongo
    links: ['mongo-service:mongo']
    environment:
      CONN_NAME: 'localConnection'
      DB_HOST: 'mongo'
      HOST: 0.0.0.0
    ports:
      - 1234:1234

  business-configuration-service:
    image: com.swapnilsankla/business-configuration
    container_name: business-configuration
    depends_on:
      - mongo-service
    environment:
      - MONGO_DB_HOST=mongo

  customer-service:
    image: com.swapnilsankla/customer-service
    container_name: customer-service
    depends_on:
      - kafka
      - business-configuration-service
      - tracing
    ports:
      - 8081:8081
    environment:
      - MONGO_URL=mongodb://mongo:27017/customer-service
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831

  loan-gateway-service:
    image: com.swapnilsankla/loan-gateway
    container_name: loan-gateway
    depends_on:
      - kafka
      - tracing
    ports:
      - 8082:8082
    environment:
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831

  loan-offer-service:
    image: com.swapnilsankla/loan-offer-service
    container_name: loan-offer-service
    depends_on:
      - kafka
      - business-configuration-service
      - tracing
    ports:
      - 8083:8083
    environment:
      - MONGO_URL=mongodb://mongo:27017/loan-offer-service
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831
    networks:
      monitoring:
        aliases:
          - loan-offer-service

  screening-service:
    image: com.swapnilsankla/screening-service
    container_name: screening-service
    depends_on:
      - kafka
      - business-configuration-service
      - tracing
    ports:
      - 8084:8084
    environment:
      - MONGO_URL=mongodb://mongo:27017/screening-service
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831

  loan-fulfilment-service:
    image: com.swapnilsankla/loan-fulfilment-service
    container_name: loan-fulfilment-service
    depends_on:
      - kafka
      - mongo-service
      - tracing
    ports:
      - 8085:8085
    environment:
      - KAFKA_URL=kafka:9092
      - TRACER_HOST=tracing
      - TRACER_PORT=6831

  kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
      - "7071:7071"
    expose:
      - 2181
      - 9092
      - 7071
    environment:
      - ADVERTISED_HOST:localhost
      - ADVERTISED_PORT:9092
      - KAFKA_ADVERTISED_HOST_NAME:kafka
      - KAFKA_CREATE_TOPICS:"needLoanEvent:1:1,loanOfferDataAvailableForLoanProcessing:1:1,customerDataAvailableForLoanProcessing:1:1,screeningDataAvailableForLoanProcessing:1:1"
    networks:
      monitoring:
        aliases:
          - kafka

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    links:
      - kafka
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    depends_on:
      - customer-service

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - customer-service

  tracing:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 5775:5775/udp

networks:
  monitoring: