apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger
  labels:
    name: "jaeger"
spec:
  selector:
    matchLabels:
      name: "jaeger"
  template:
    metadata:
      labels:
        name: "jaeger"
    spec:
      containers:
      - name: jaeger    
        image: jaegertracing/all-in-one
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 6831
          protocol: UDP
        - containerPort: 5775
          protocol: UDP
