apiVersion: batch/v1
kind: Job
metadata:
  name: business-configuration
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - image: com.swapnilsankla/business-configuration
        name: business-configuration
        imagePullPolicy: IfNotPresent 
        env:
        - name: MONGO_DB_HOST
          value: mongo